DROP DATABASE IF EXISTS pizzashop_db;
-- Creating database
CREATE DATABASE pizzashop_db;

-- Connecting to database
\c pizzashop_db;

-- Creating pizzas table
CREATE TABLE IF NOT EXISTS pizzas(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255),
  _created_at date NOT NULL,
  _updated_at date
);


-- Creating toppings table
CREATE TABLE IF NOT EXISTS toppings(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255),
  _created_at date NOT NULL,
  _updated_at date
);

-- Creating toppings-pizzas relational table
CREATE TABLE IF NOT EXISTS toppings_pizza(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_pizza INTEGER REFERENCES pizzas(id),
  id_topping INTEGER REFERENCES toppings(id),
  _created_at date NOT NULL,
  _updated_at date
);

-- Inserting test data
INSERT INTO pizzas (name, _created_at) VALUES ('Hawaiian', NOW()), ('Irish', NOW());
INSERT INTO toppings (name, _created_at) VALUES ('Pepperoni', NOW()), ('Potatoes', NOW()), ('Cheddar Cheese', NOW());
INSERT INTO toppings_pizza (id_pizza, id_topping, _created_at) VALUES (1, 1, NOW()), (1, 2, NOW()), (2, 2, NOW()), (1, 3, NOW());
